// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectOBS(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectOBS'](arg1, arg2, arg3);
}

export function EmergencyStop() {
  return window['go']['main']['App']['EmergencyStop']();
}

export function GetActivity() {
  return window['go']['main']['App']['GetActivity']();
}

export function GetBridgeStatus() {
  return window['go']['main']['App']['GetBridgeStatus']();
}

export function IsHalted() {
  return window['go']['main']['App']['IsHalted']();
}

export function ResumeAfterStop() {
  return window['go']['main']['App']['ResumeAfterStop']();
}

export function SendRconCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRconCommand'](arg1, arg2, arg3, arg4);
}

export function SimulateKeyPress(arg1, arg2, arg3) {
  return window['go']['main']['App']['SimulateKeyPress'](arg1, arg2, arg3);
}
