// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function ConnectOBS(arg1:string,arg2:number,arg3:string):Promise<boolean>;

export function GetBridgeStatus():Promise<bridge.Status>;

export function SendRconCommand(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SimulateKeyPress(arg1:number,arg2:number,arg3:number):Promise<void>;
